#
# Copyright (C) 2020 Grakn Labs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/linux.sh
      - run: bash ./linux.sh && rm ./linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/dependencies/master/tool/bazelinstall/rbe.sh
      - run: bash ./rbe.sh && rm ./rbe.sh          

  run-bazel:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_dependencies//tool/bazelrun:rbe -- << parameters.command >>

jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run: bazel run @graknlabs_dependencies//tool/checkstyle:test-coverage
      - run-bazel:
          command: bazel build //...
      - run:
          name: Verify dependencies/maven/artifacts.snapshot
          command: |
            dependencies/maven/update.sh
            git diff --exit-code dependencies/maven/artifacts.snapshot

  test-integration:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run-bazel:
          command: bazel test //test:grakn-console-it --test_output=errors

  build-analysis:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run: |
          SONARCLOUD_CODE_ANALYSIS_CREDENTIAL=$SONARCLOUD_CREDENTIAL \
            bazel run @graknlabs_dependencies//tool/sonarcloud:code-analysis -- \
            --project-key graknlabs_console --branch=$CIRCLE_BRANCH --commit-id=$CIRCLE_SHA1

  deploy-artifact-snapshot:
    machine: true
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run: |
          export DEPLOY_ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //:deploy-console-artifact -- snapshot

  deploy-apt-snapshot:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run: |
          export DEPLOY_APT_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_APT_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //:deploy-apt -- snapshot

  deploy-rpm-snapshot:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run: sudo apt-get update && sudo apt-get install rpm
      - run: |
          export DEPLOY_RPM_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_RPM_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(git rev-parse HEAD) //:deploy-rpm -- snapshot

  release-approval:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - install-bazel
      - checkout
      - run: |
          export RELEASE_APPROVAL_USERNAME=$REPO_GITHUB_USERNAME
          export RELEASE_APPROVAL_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tool/release:approval

  release-validate:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - install-bazel
      - checkout
      - run: |
          bazel run @graknlabs_dependencies//tool/release:validate-deps -- \
            graknlabs_common graknlabs_graql graknlabs_client_java

  deploy-artifact:
    machine: true
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run: |
          export DEPLOY_ARTIFACT_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_ARTIFACT_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(cat VERSION) //:deploy-console-artifact -- release

  deploy-github:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run: |
          pip install certifi
          export RELEASE_NOTES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tool/release:create-notes -- console $(cat VERSION) ./RELEASE_TEMPLATE.md
      - run: |
          export DEPLOY_GITHUB_TOKEN=$REPO_GITHUB_TOKEN
          bazel run --define version=$(cat VERSION) //:deploy-github -- $CIRCLE_SHA1

  deploy-apt:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run: cat VERSION
      - run: |
          export DEPLOY_APT_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_APT_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(cat VERSION) //:deploy-apt -- release

  deploy-rpm:
    machine: 
      image: ubuntu-1604:201903-01
    working_directory: ~/console
    steps:
      - install-bazel
      - checkout
      - run: sudo apt-get update && sudo apt-get install rpm
      - run: |
          export DEPLOY_RPM_USERNAME=$REPO_GRAKN_USERNAME
          export DEPLOY_RPM_PASSWORD=$REPO_GRAKN_PASSWORD
          bazel run --define version=$(cat VERSION) //:deploy-rpm -- release

  sync-dependencies-release:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - install-bazel
      - checkout
      - run: |
          export SYNC_DEPENDENCIES_TOKEN=$REPO_GITHUB_TOKEN
          bazel run @graknlabs_dependencies//tool/sync:dependencies -- \
          --source console@$(cat VERSION) \
          --targets grakn:master

  release-cleanup:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: git push --delete https://$REPO_GITHUB_TOKEN@github.com/graknlabs/console $CIRCLE_BRANCH

workflows:
  console:
    jobs:
      - build:
          filters:
            branches:
              ignore: console-release-branch
      - test-integration:
          filters:
            branches:
              ignore: console-release-branch
      - build-analysis:
          filters:
            branches:
              only: master
      - deploy-artifact-snapshot:
          filters:
            branches:
              only: master
          requires:
            - build
            - build-analysis
            - test-integration
      - deploy-apt-snapshot:
          filters:
            branches:
              only: master
          requires:
            - build
            - build-analysis
            - test-integration
      - deploy-rpm-snapshot:
          filters:
            branches:
              only: master
          requires:
            - build
            - build-analysis
            - test-integration
      - release-approval:
          filters:
            branches:
              only: master
          requires:
            - deploy-artifact-snapshot
            - deploy-apt-snapshot
            - deploy-rpm-snapshot

  console-release:
    jobs:
      - release-validate:
          filters:
            branches:
              only: console-release-branch
      - deploy-github:
          filters:
            branches:
              only: console-release-branch
          requires:
            - release-validate
      - deploy-approval:
          type: approval
          requires:
            - deploy-github
          filters:
            branches:
              only: console-release-branch
      - deploy-artifact:
          filters:
            branches:
              only: console-release-branch
          requires:
            - deploy-approval
      - deploy-apt:
          filters:
            branches:
              only: console-release-branch
          requires:
            - deploy-approval
      - deploy-rpm:
          filters:
            branches:
              only: console-release-branch
          requires:
            - deploy-approval
      - release-cleanup:
          filters:
            branches:
              only: console-release-branch
          requires:
            - deploy-artifact
            - deploy-apt
            - deploy-rpm
